leftnav:
- identifier: 89dab3cd-a2de-f3f8-2d0a-0fbe5bb55f17
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: external-472d4a8ff9f84a74a72abeac446d7696
  name: Online Publication
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+6.036+1T2019/about
  weight: 1000
